
name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarxDev/ast-github-action@master #Github Action version
        with:
          project_name: Shaul_test_GitHubAction
          cx_tenant: dp_wp_account
          base_uri: https://eu.ast.checkmarx.net/ 
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
          scan_types: sast,kics,sca
